/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // Casino Design System
        'felt-green': '#0B3D2E',
        'felt-green-light': '#1A5C42',
        'felt-green-dark': '#072A1F',
        'gold': '#D4A830',
        'gold-light': '#F0C94A',
        'gold-dark': '#A68324',
        'burgundy': '#7B1F3C',
        'burgundy-dark': '#4A1224',
        'emerald-game': '#10B981',
        'emerald-dark': '#059669',
        'ruby': '#DC2626',
        'ruby-dark': '#B91C1C',
        'bg-dark': '#0A0E1A',
        'bg-card': '#141B2D',
        'bg-card-hover': '#1C2540',
        'bg-elevated': '#1E2945',
        'border-subtle': '#2A3655',
        'border-gold': 'rgba(212,168,48,0.5)',
        'text-primary': '#F0F0F5',
        'text-secondary': '#8B95B8',
        'text-gold': '#D4A830',
        'suit-clubs': '#1A1A1A',
        'suit-spades': '#1A1A1A',
        'suit-hearts': '#DC2626',
        'suit-diamonds': '#DC2626',
        'team-red': '#DC2626',
        'team-blue': '#2563EB',
        'chip-white': '#F5F5F5',
        'chip-red': '#DC2626',
        'chip-blue': '#2563EB',
        'chip-green': '#059669',
        'chip-black': '#1A1A1A',
        // shadcn compatibility
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        'display': ['Cinzel', 'Georgia', 'serif'],
        'body': ['Inter', 'system-ui', 'sans-serif'],
        'mono-game': ['Roboto Mono', 'monospace'],
      },
      spacing: {
        'space-1': '4px',
        'space-2': '8px',
        'space-3': '12px',
        'space-4': '16px',
        'space-6': '24px',
        'space-8': '32px',
        'space-10': '40px',
        'space-12': '48px',
        'space-16': '64px',
      },
      borderRadius: {
        'sm-game': '4px',
        'md-game': '8px',
        'lg-game': '12px',
        'xl-game': '16px',
        'card': '6px',
        'full': '9999px',
        xl: "calc(var(--radius) + 4px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xs: "calc(var(--radius) - 6px)",
      },
      boxShadow: {
        'sm-game': '0 1px 3px rgba(0,0,0,0.3)',
        'md-game': '0 4px 12px rgba(0,0,0,0.4)',
        'lg-game': '0 8px 24px rgba(0,0,0,0.5)',
        'xl-game': '0 16px 48px rgba(0,0,0,0.6)',
        'gold': '0 0 20px rgba(212,168,48,0.3)',
        'gold-lg': '0 0 40px rgba(212,168,48,0.4)',
        'card': '0 2px 8px rgba(0,0,0,0.5), inset 0 0 2px rgba(255,255,255,0.1)',
        'chip': '0 2px 4px rgba(0,0,0,0.4), inset 0 0 0 2px rgba(255,255,255,0.15)',
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
      },
      transitionTimingFunction: {
        'ease-out-game': 'cubic-bezier(0.16, 1, 0.3, 1)',
        'ease-in-out-game': 'cubic-bezier(0.65, 0, 0.35, 1)',
        'ease-spring': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
        'ease-smooth': 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
      transitionDuration: {
        'instant': '100ms',
        'fast': '200ms',
        'normal': '300ms',
        'slow': '500ms',
        'dramatic': '800ms',
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
        "gold-shine": {
          "0%": { backgroundPosition: "-200% center" },
          "100%": { backgroundPosition: "200% center" },
        },
        "float": {
          "0%, 100%": { transform: "translateY(0) rotate(0deg)" },
          "50%": { transform: "translateY(-20px) rotate(5deg)" },
        },
        "pulse-gold": {
          "0%, 100%": { boxShadow: "0 0 20px rgba(212,168,48,0.3)" },
          "50%": { boxShadow: "0 0 40px rgba(212,168,48,0.6)" },
        },
        "fade-in-up": {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "scale-in": {
          "0%": { opacity: "0", transform: "scale(0.8)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        "slide-up": {
          "0%": { transform: "translateY(100%)" },
          "100%": { transform: "translateY(0)" },
        },
        "bounce-coin": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-12px)" },
        },
        "particle-float": {
          "0%": { transform: "translateY(100vh) rotate(0deg)", opacity: "0" },
          "10%": { opacity: "1" },
          "90%": { opacity: "1" },
          "100%": { transform: "translateY(-100vh) rotate(720deg)", opacity: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
        "gold-shine": "gold-shine 3s linear infinite",
        "float": "float 6s ease-in-out infinite",
        "pulse-gold": "pulse-gold 3s ease-in-out infinite",
        "fade-in-up": "fade-in-up 0.5s ease-out-game forwards",
        "scale-in": "scale-in 0.8s ease-spring forwards",
        "slide-up": "slide-up 0.4s ease-out-game forwards",
        "bounce-coin": "bounce-coin 1.5s ease-spring infinite",
        "particle-float": "particle-float 25s linear infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
